version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    links:
      - wordpress
    # Restart https-portal on failure or after Docker host restart.
    restart: always
    environment:
      # Forward wordpress.example.com to the WordPress container.
      # You can set up multiple domains at once.
      DOMAINS: 'https-portal-test.steveltn.me -> http://wordpress'
      STAGE: production
      # Using staging server by default, for there is a rate limit on production.
      # Uncomment to use Let's Encrypt production server.
      # STAGE: production
    volumes:
      - https-portal-data:/var/lib/https-portal

  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: '<a secure password>'
      WORDPRESS_DB_USER: wordpress
    links:
      - db:mysql

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: '<a secure password>'
      MYSQL_USER: wordpress
    volumes:
      - db-data:/var/lib/mysql

volumes:
  https-portal-data:
  db-data:
