version: '3'

services:
https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  links:
    - wordpress
  restart: always
  environment:
    DOMAINS: 'ec2-13-126-11-83.ap-south-1.compute.amazonaws.com -> https://ec2-13-126-11-83.ap-south-1.compute.amazonaws.com:443'
    # STAGE: 'production' # Don't use production until staging works
    # FORCE_RENEW: 'true'

wordpress:
  image: wordpress
  links:
    - db:mysql

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: 'delli3'

volumes:
  db_data: {}
  wp_data: {}
