version: '3'

services:

  mysql:
    image: mysql:5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    build: docker/wordpress
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wp-content
      - ./root/plugin:/var/www/html/wp-content/${TYPE}s/wp-${NAME}-${TYPE}
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USERNAME: "root"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data: {}
  wp_data: {}
